# Form implementation generated from reading ui file 'src/about.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_About_Dialog(object):
    def setupUi(self, About_Dialog):
        About_Dialog.setObjectName("About_Dialog")
        About_Dialog.setEnabled(True)
        About_Dialog.resize(460, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(About_Dialog.sizePolicy().hasHeightForWidth())
        About_Dialog.setSizePolicy(sizePolicy)
        self.textEdit1 = QtWidgets.QTextEdit(parent=About_Dialog)
        self.textEdit1.setGeometry(QtCore.QRect(0, 0, 460, 420))
        self.textEdit1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textEdit1.setReadOnly(True)
        self.textEdit1.setObjectName("textEdit1")

        self.retranslateUi(About_Dialog)
        QtCore.QMetaObject.connectSlotsByName(About_Dialog)

    def retranslateUi(self, About_Dialog):
        _translate = QtCore.QCoreApplication.translate
        About_Dialog.setWindowTitle(_translate("About_Dialog", "About IMGenAI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    About_Dialog = QtWidgets.QDialog()
    ui = Ui_About_Dialog()
    ui.setupUi(About_Dialog)
    About_Dialog.show()
    sys.exit(app.exec())
