from PyQt6 import QtCore, QtGui, QtWidgets
from ImageView import ImageView


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
		MainWindow.resize(1000, 762)
		MainWindow.setIconSize(QtCore.QSize(24, 24))
		self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
		self.widget1.setGeometry(QtCore.QRect(10, 10, 250, 663))
		self.widget1.setObjectName("widget1")
		self.label5 = QtWidgets.QLabel(parent=self.widget1)
		self.label5.setGeometry(QtCore.QRect(0, 390, 197, 16))
		self.label5.setObjectName("label5")
		self.spinBox4 = QtWidgets.QSpinBox(parent=self.widget1)
		self.spinBox4.setGeometry(QtCore.QRect(200, 573, 50, 22))
		self.spinBox4.setMinimum(1)
		self.spinBox4.setMaximum(30)
		self.spinBox4.setProperty("value", 7)
		self.spinBox4.setObjectName("spinBox4")
		self.textEdit2 = QtWidgets.QTextEdit(parent=self.widget1)
		self.textEdit2.setGeometry(QtCore.QRect(0, 215, 250, 100))
		self.textEdit2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhMultiLine)
		self.textEdit2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
		self.textEdit2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
		self.textEdit2.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
		self.textEdit2.setObjectName("textEdit2")
		self.lineEdit2 = QtWidgets.QLineEdit(parent=self.widget1)
		self.lineEdit2.setGeometry(QtCore.QRect(0, 20, 250, 25))
		self.lineEdit2.setText("")
		self.lineEdit2.setObjectName("lineEdit2")
		self.spinBox2 = QtWidgets.QSpinBox(parent=self.widget1)
		self.spinBox2.setGeometry(QtCore.QRect(200, 449, 50, 22))
		self.spinBox2.setMinimum(64)
		self.spinBox2.setMaximum(2048)
		self.spinBox2.setSingleStep(8)
		self.spinBox2.setProperty("value", 512)
		self.spinBox2.setObjectName("spinBox2")
		self.lineEdit1 = QtWidgets.QLineEdit(parent=self.widget1)
		self.lineEdit1.setGeometry(QtCore.QRect(0, 350, 190, 25))
		self.lineEdit1.setObjectName("lineEdit1")
		self.spinBox1 = QtWidgets.QSpinBox(parent=self.widget1)
		self.spinBox1.setGeometry(QtCore.QRect(200, 387, 50, 22))
		self.spinBox1.setMinimum(1)
		self.spinBox1.setMaximum(150)
		self.spinBox1.setProperty("value", 20)
		self.spinBox1.setObjectName("spinBox1")
		self.label2 = QtWidgets.QLabel(parent=self.widget1)
		self.label2.setGeometry(QtCore.QRect(0, 60, 250, 16))
		self.label2.setObjectName("label2")
		self.label1 = QtWidgets.QLabel(parent=self.widget1)
		self.label1.setGeometry(QtCore.QRect(0, 0, 250, 16))
		self.label1.setObjectName("label1")
		self.horizontalSlider2 = QtWidgets.QSlider(parent=self.widget1)
		self.horizontalSlider2.setGeometry(QtCore.QRect(0, 477, 250, 22))
		self.horizontalSlider2.setMinimum(64)
		self.horizontalSlider2.setMaximum(2048)
		self.horizontalSlider2.setSingleStep(8)
		self.horizontalSlider2.setProperty("value", 512)
		self.horizontalSlider2.setOrientation(QtCore.Qt.Orientation.Horizontal)
		self.horizontalSlider2.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
		self.horizontalSlider2.setObjectName("horizontalSlider2")
		self.horizontalSlider1 = QtWidgets.QSlider(parent=self.widget1)
		self.horizontalSlider1.setGeometry(QtCore.QRect(0, 415, 250, 22))
		self.horizontalSlider1.setMinimum(1)
		self.horizontalSlider1.setMaximum(150)
		self.horizontalSlider1.setProperty("value", 20)
		self.horizontalSlider1.setOrientation(QtCore.Qt.Orientation.Horizontal)
		self.horizontalSlider1.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
		self.horizontalSlider1.setObjectName("horizontalSlider1")
		self.label3 = QtWidgets.QLabel(parent=self.widget1)
		self.label3.setGeometry(QtCore.QRect(0, 195, 250, 16))
		self.label3.setObjectName("label3")
		self.spinBox3 = QtWidgets.QSpinBox(parent=self.widget1)
		self.spinBox3.setGeometry(QtCore.QRect(200, 511, 50, 22))
		self.spinBox3.setMinimum(64)
		self.spinBox3.setMaximum(2048)
		self.spinBox3.setSingleStep(8)
		self.spinBox3.setProperty("value", 512)
		self.spinBox3.setObjectName("spinBox3")
		self.label8 = QtWidgets.QLabel(parent=self.widget1)
		self.label8.setGeometry(QtCore.QRect(0, 576, 197, 16))
		self.label8.setObjectName("label8")
		self.pushButton4 = QtWidgets.QPushButton(parent=self.widget1)
		self.pushButton4.setGeometry(QtCore.QRect(0, 638, 250, 25))
		self.pushButton4.setObjectName("pushButton4")
		self.pushButton3 = QtWidgets.QPushButton(parent=self.widget1)
		self.pushButton3.setGeometry(QtCore.QRect(223, 349, 27, 27))
		self.pushButton3.setObjectName("pushButton3")
		self.horizontalSlider4 = QtWidgets.QSlider(parent=self.widget1)
		self.horizontalSlider4.setGeometry(QtCore.QRect(0, 601, 250, 22))
		self.horizontalSlider4.setMinimum(1)
		self.horizontalSlider4.setMaximum(30)
		self.horizontalSlider4.setSingleStep(1)
		self.horizontalSlider4.setProperty("value", 7)
		self.horizontalSlider4.setOrientation(QtCore.Qt.Orientation.Horizontal)
		self.horizontalSlider4.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
		self.horizontalSlider4.setObjectName("horizontalSlider4")
		self.label4 = QtWidgets.QLabel(parent=self.widget1)
		self.label4.setGeometry(QtCore.QRect(0, 330, 250, 16))
		self.label4.setObjectName("label4")
		self.textEdit1 = QtWidgets.QTextEdit(parent=self.widget1)
		self.textEdit1.setGeometry(QtCore.QRect(0, 80, 250, 100))
		self.textEdit1.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhMultiLine)
		self.textEdit1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
		self.textEdit1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
		self.textEdit1.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
		self.textEdit1.setObjectName("textEdit1")
		self.horizontalSlider3 = QtWidgets.QSlider(parent=self.widget1)
		self.horizontalSlider3.setGeometry(QtCore.QRect(0, 539, 250, 22))
		self.horizontalSlider3.setMinimum(64)
		self.horizontalSlider3.setMaximum(2048)
		self.horizontalSlider3.setSingleStep(8)
		self.horizontalSlider3.setProperty("value", 512)
		self.horizontalSlider3.setOrientation(QtCore.Qt.Orientation.Horizontal)
		self.horizontalSlider3.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
		self.horizontalSlider3.setObjectName("horizontalSlider3")
		self.pushButton2 = QtWidgets.QPushButton(parent=self.widget1)
		self.pushButton2.setGeometry(QtCore.QRect(193, 349, 27, 27))
		self.pushButton2.setObjectName("pushButton2")
		self.label6 = QtWidgets.QLabel(parent=self.widget1)
		self.label6.setGeometry(QtCore.QRect(0, 452, 197, 16))
		self.label6.setObjectName("label6")
		self.label7 = QtWidgets.QLabel(parent=self.widget1)
		self.label7.setGeometry(QtCore.QRect(0, 514, 197, 16))
		self.label7.setObjectName("label7")

		# self.image = QtWidgets.QLabel(parent=self.centralwidget)
		# self.image.setEnabled(True)
		# self.image.setGeometry(QtCore.QRect(270, 10, 720, 720))
		# self.image.setAutoFillBackground(False)
		# self.image.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
		# self.image.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
		# self.image.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
		# self.image.setLineWidth(1)
		# self.image.setMidLineWidth(0)
		# self.image.setText("")
		# self.image.setTextFormat(QtCore.Qt.TextFormat.AutoText)
		# self.image.setScaledContents(False)
		# self.image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		# self.image.setWordWrap(False)
		# self.image.setOpenExternalLinks(False)
		# self.image.setObjectName("image")

		self.image = ImageView(parent=self.centralwidget)
		self.image.setEnabled(True)
		self.image.setGeometry(QtCore.QRect(270, 10, 720, 720))
		self.image.setAutoFillBackground(False)
		self.image.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
		self.image.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
		self.image.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
		self.image.setLineWidth(1)
		self.image.setMidLineWidth(0)
		self.image.setText("")
		self.image.setTextFormat(QtCore.Qt.TextFormat.AutoText)
		self.image.setScaledContents(False)
		self.image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		self.image.setWordWrap(False)
		self.image.setOpenExternalLinks(False)
		self.image.setObjectName("image")

		MainWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
		self.statusbar.setEnabled(True)
		self.statusbar.setStatusTip("")
		self.statusbar.setSizeGripEnabled(True)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
		self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
		self.menuBar.setObjectName("menuBar")
		self.menua = QtWidgets.QMenu(parent=self.menuBar)
		self.menua.setObjectName("menua")
		self.menuSettings = QtWidgets.QMenu(parent=self.menuBar)
		self.menuSettings.setObjectName("menuSettings")
		self.menuHelp = QtWidgets.QMenu(parent=self.menuBar)
		self.menuHelp.setObjectName("menuHelp")
		MainWindow.setMenuBar(self.menuBar)
		self.save_images = QtGui.QAction(parent=MainWindow)
		self.save_images.setCheckable(True)
		self.save_images.setChecked(True)
		self.save_images.setEnabled(True)
		self.save_images.setObjectName("save_images")
		self.save_prompts = QtGui.QAction(parent=MainWindow)
		self.save_prompts.setCheckable(True)
		self.save_prompts.setChecked(True)
		self.save_prompts.setObjectName("save_prompts")
		self.open_prompt = QtGui.QAction(parent=MainWindow)
		self.open_prompt.setObjectName("open_prompt")
		self.save_prompt = QtGui.QAction(parent=MainWindow)
		self.save_prompt.setObjectName("save_prompt")
		self.actionWidget = QtGui.QAction(parent=MainWindow)
		self.actionWidget.setCheckable(True)
		self.actionWidget.setChecked(True)
		self.actionWidget.setObjectName("actionWidget")
		self.toggle_sidebar = QtGui.QAction(parent=MainWindow)
		self.toggle_sidebar.setCheckable(True)
		self.toggle_sidebar.setChecked(True)
		self.toggle_sidebar.setObjectName("toggle_sidebar")
		self.reset_prompt = QtGui.QAction(parent=MainWindow)
		self.reset_prompt.setObjectName("reset_prompt")
		self.configuration = QtGui.QAction(parent=MainWindow)
		self.configuration.setObjectName("configuration")
		self.NSFW_content = QtGui.QAction(parent=MainWindow)
		self.NSFW_content.setCheckable(True)
		self.NSFW_content.setChecked(False)
		self.NSFW_content.setObjectName("NSFW_content")
		self.menua.addAction(self.open_prompt)
		self.menua.addAction(self.save_prompt)
		self.menuSettings.addAction(self.toggle_sidebar)
		self.menuSettings.addSeparator()
		self.menuSettings.addAction(self.save_images)
		self.menuSettings.addAction(self.save_prompts)
		self.menuSettings.addSeparator()
		self.menuSettings.addAction(self.NSFW_content)
		self.menuSettings.addAction(self.configuration)
		self.menuSettings.addAction(self.reset_prompt)
		self.menuBar.addAction(self.menua.menuAction())
		self.menuBar.addAction(self.menuSettings.menuAction())
		self.menuBar.addAction(self.menuHelp.menuAction())

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "IMGenAI"))
		self.label5.setText(_translate("MainWindow", "Sampling steps"))
		self.lineEdit2.setPlaceholderText(_translate("MainWindow", "https://..."))
		self.lineEdit1.setText(_translate("MainWindow", "-1"))
		self.label2.setText(_translate("MainWindow", "Prompt"))
		self.label1.setText(_translate("MainWindow", "Enter server address"))
		self.label3.setText(_translate("MainWindow", "Negative prompt"))
		self.label8.setText(_translate("MainWindow", "Guidance scale (CFG)"))
		self.pushButton4.setText(_translate("MainWindow", "Generate"))
		self.pushButton3.setText(_translate("MainWindow", "🔄"))
		self.label4.setText(_translate("MainWindow", "Seed"))
		self.pushButton2.setText(_translate("MainWindow", "❔"))
		self.label6.setText(_translate("MainWindow", "Width"))
		self.label7.setText(_translate("MainWindow", "Height"))
		self.menua.setTitle(_translate("MainWindow", "File"))
		self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
		self.menuHelp.setTitle(_translate("MainWindow", "Help"))
		self.save_images.setText(_translate("MainWindow", "Save images"))
		self.save_prompts.setText(_translate("MainWindow", "Save prompts"))
		self.open_prompt.setText(_translate("MainWindow", "Open prompt"))
		self.save_prompt.setText(_translate("MainWindow", "Save prompt"))
		self.actionWidget.setText(_translate("MainWindow", "Widget"))
		self.toggle_sidebar.setText(_translate("MainWindow", "Sidebar"))
		self.reset_prompt.setText(_translate("MainWindow", "Reset prompt"))
		self.configuration.setText(_translate("MainWindow", "Configuration"))
		self.NSFW_content.setText(_translate("MainWindow", "Allow NSFW content"))
